server.admintool/Models/CommandInfo.cs
namespace server.admintool.Models
{
  public class CommandInfo
  {
    public string name { get; set; }
    public string description { get; set; }
    public string action { get; set; }
  }
}

server.admintool/Models/ConfigItem.cs
namespace server.admintool.Models
{
  public class ConfigItem
  {
    public string key { get; set; }
    public string value { get; set; }
  }
}

server.admintool/Models/ErrorViewModel.cs
namespace server.admintool.Models
{
  public class ErrorViewModel
  {
    public string request_id { get; set; }
    public string error_message { get; set; }


    public bool showRequestId => !string.IsNullOrEmpty( request_id );
  }
}

server.admintool/Models/FeatureInfo.cs
namespace server.admintool.Models
{
  public class FeatureInfo
  {
    public string feature_id { get; set; }
    public string action_name { get; set; }
    public string action { get; set; }
  }
}

server.admintool/Controllers/ServerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using server.admintool.Models;
using server.admintool.Services;
using System;


namespace server.admintool.Controllers
{
  public class ServerController : Controller
  {
    private readonly ILogger<ServerController> _logger;
    private readonly ServerService _server_service;
    private static readonly Version _api_version = new Version( 1, 0 );

    public ServerController( ILogger<ServerController> logger, ServerService server_service )
    {
      _logger = logger;
      _server_service = server_service;
    }


    public IActionResult Index()
    {
      return View();
    }

    [HttpPost]
    public IActionResult ServerMenu( string authority )
    {
      Version server_api_verion = _server_service.getApiVersion( authority );
      if ( server_api_verion != _api_version )
        return View( new ErrorViewModel { error_message = $"admin api verion: {_api_version.ToString( 2 )}, server api version: {server_api_verion.ToString( 2 )}" } );

      TempData[CommonConstants.HOST_FIELD_NAME] = authority;
      return View();
    }

    [ResponseCache( Duration = 0, Location = ResponseCacheLocation.None, NoStore = true )]
    public IActionResult Error()
    {
      return View( new ErrorViewModel { request_id = Activity.Current?.Id ?? HttpContext.TraceIdentifier } );
    }

    public IActionResult GetSelfPid()
    {
      return View();
    }

    public IActionResult GetGlobalFeatureStates()
    {
      return View();
    }

    [HttpPost]
    public IActionResult GetGlobalFeatureStates( string feature_action )
    {
      string payload = _server_service.switchFeatureState( feature_action );
      if ( payload != CommonConstants.RESPONSE_CMD_COMPLETED_SUCCESSFULLY )
        return RedirectToAction( "Error" );

      return RedirectToAction( "GetGlobalFeatureStates" );
    }

    public IActionResult Stop()
    {
      _server_service.stopServer( TempData[CommonConstants.HOST_FIELD_NAME].ToString() );
      return RedirectToAction( "Index" );
    }

    public IActionResult GetConfig()
    {
      return View( "GetServerConfig" );
    }

    public IActionResult SetGlobalLogLevel( string log_level )
    {
      _server_service.setGlobalLogLevel( TempData[CommonConstants.HOST_FIELD_NAME].ToString(), log_level );
      return RedirectToAction( "GetConfig" );
    }

    public IActionResult FindPerson()
    {
      return View();
    }

    public IActionResult ReloadPersonInfo( string feature_action )
    {
      string person_id = TempData.Peek( CommonConstants.ARG_PERSON_ID )?.ToString();
      if ( string.IsNullOrEmpty( person_id ) )
        return RedirectToAction( "FindPerson" );

      string payload = _server_service.switchFeatureState( feature_action );
      if ( payload != CommonConstants.RESPONSE_CMD_COMPLETED_SUCCESSFULLY )
        return RedirectToAction( "Error" );

      return View( "ShowPersonInfo", person_id );
    }

    public IActionResult ShowPersonInfo( string person_id )
    {
      if ( string.IsNullOrEmpty( person_id ) )
      {
        person_id = TempData[CommonConstants.ARG_PERSON_ID]?.ToString();
        if ( string.IsNullOrEmpty( person_id ) )
          return RedirectToAction( "FindPerson" );
      } else
        TempData[CommonConstants.ARG_PERSON_ID] = person_id;

      return View( (object)person_id );
    }
  }
}

server.admintool/Views/Server/FindPerson.cshtml
@{
    ViewData["Title"] = "FindPerson";
}

<h1>@ViewData["Title"]</h1>

<table class="table">
    <tr>
        <td style="width:20%">
            @await Component.InvokeAsync( nameof( NavMenu ) )
        </td>
        <td>
            <form asp-action="ShowPersonInfo" method="post">
                <div class="form-group">
                    <label>Person ID:</label>
                    <input type="text" id="person_id" name="person_id" class="form-control" required minlength="1"/>
                </div>
                <div class="text-center">
                    <button type="submit" class="btn btn-primary">Find</button>
                </div>
            </form>
        </td>
    </tr>
</table>

server.admintool/Views/Server/GetGlobalFeatureStates.cshtml
@{
    ViewData["Title"] = "GetFeatureStates";
}

<h1>@ViewData["Title"]</h1>

<table class="table">
    <tr>
        <td style="width:20%">
            @await Component.InvokeAsync( nameof( NavMenu ) )
        </td>
        <td>
            @await Component.InvokeAsync( nameof( FeatureStates ) )
        </td>
    </tr>
</table>

server.admintool/Views/Server/GetSelfPid.cshtml
@model int
@{
    ViewData["Title"] = "GetSelfPid";
}

<h1>@ViewData["Title"]</h1>

<table class="table">
    <tr>
        <td style="width:20%">
            @await Component.InvokeAsync( nameof( NavMenu ) )
        </td>
        <td>
            @await Component.InvokeAsync( nameof( ServerPid ) )
        </td>
    </tr>
</table>

server.admintool/Views/Server/GetServerConfig.cshtml
@{
    ViewData["Title"] = "GetConfig";
}

<h1>@ViewData["Title"]</h1>

<table class="table">
    <tr>
        <td style="width:20%">
            @await Component.InvokeAsync( nameof( NavMenu ) )
        </td>
        <td>
            @await Component.InvokeAsync( nameof( ServerConfig ) )
        </td>
    </tr>
</table>

server.admintool/Views/Server/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<form asp-action="ServerMenu" method="post">
    <div class="form-group">
        <label>Host:</label>
        <input type="text" id="authority" name="authority" class="form-control" placeholder="http://192.168.1.1:25752/" required minlength="10" />
    </div>
    <div class="text-center">
        <button type="submit" class="btn btn-primary">Connect</button>
    </div>
</form>

server.admintool/Views/Server/ServerMenu.cshtml
@{
    ViewData["Title"] = "ServerMenu";
}

<table class="table">
    <tr>
        <td style="width:20%">
            @await Component.InvokeAsync( nameof( NavMenu ) )
        </td>
        <td>
        </td>
    </tr>
</table>

server.admintool/Views/Server/ShowPersonInfo.cshtml
@model string
@{
    ViewData["Title"] = "ShowPersonInfo";
}

<h1>@ViewData["Title"]</h1>

<table class="table">
    <tr>
        <td style="width:20%">
            @await Component.InvokeAsync( nameof( NavMenu ) )
        </td>
        <td>
            <div>
                <b> Person ID: @Model</b>
            </div>
            <br>
            @await Component.InvokeAsync( nameof( FeatureStates ), Model)
        </td>
    </tr>
</table>

server.admintool/Views/Shared/Components/FeatureStates/Default.cshtml
@model IEnumerable<FeatureInfo>

<div >
    <table class="table">
        <thead>
            <tr>
                <th> FEATURE ID</th>
                <th> STATE</th>
            <tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.feature_id
                    </td>
                    <td>
                        <form asp-action="@ViewBag.feature_action_name" asp-controller="Server" method="post">
                            <input type="hidden" value="@($"{item.action}{CommonConstants.AND_ARG_RAW}")" name="feature_action">
                            <button type="submit" class="btn @(item.action_name == "ENABLE" ? "btn-success" : "btn-danger")">@item.action_name</button>
                        </form>
                    </td>

                </tr>
            }
        </tbody>
    </table>
</div>

server.admintool/Views/Shared/Components/FeatureStates/NotFound.cshtml
@model string

<div>
    <h1 class="text-danger">NOT FOUND</h1>
</div>

server.admintool/Views/Shared/Components/NavMenu/Default.cshtml
@model IEnumerable<CommandInfo>

<a class="btn btn-block btn-secondary" asp-action="Index" asp-controller="Server"> Home </a>
<a class="btn btn-block btn-secondary" asp-action="FindPerson" asp-controller="Server"> Find person </a>
@foreach (CommandInfo cmd in Model)
{
    <a class="btn btn-block btn-secondary" asp-action="@cmd.action" asp-controller="Server">@cmd.description</a>
}

server.admintool/Views/Shared/Components/ServerConfig/Default.cshtml
@model IEnumerable<ConfigItem>

<div>
    <table class="table table-bordered table-striped">
        <thead >
            <tr>
                <th> PARAM</th>
                <th> VALUE</th>
            <tr>
        </thead>
        <tbody>
            @foreach (ConfigItem cnfg_item in Model)
            {
                <tr>
                    <td>
                        @cnfg_item.key
                    </td>
                    <td>
                        @if ( cnfg_item.key == CommonConstants.ARG_GLOBAL_LOG_LEVEL )
                            @await Component.InvokeAsync( nameof( ServerLogLevels ) )
                        else
                            @cnfg_item.value
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

server.admintool/Views/Shared/Components/ServerLogLevels/Default.cshtml
@model IEnumerable<string>

<div>
    <form method="post" asp-action="SetGlobalLogLevel" asp-controller="Server">
        <select id="log_level" name="log_level">
            @foreach (string log_level_name in Model)
            {
                if (ViewBag.curLogLevel == log_level_name)
                {
                    <option selected value="@log_level_name">@log_level_name</option>
                }
                else
                {
                    <option value="@log_level_name">@log_level_name</option>
                }
            }
        </select>
        <button type="submit" class="btn btn-primary btn-sm">change</button>
    </form>
</div>

server.admintool/Views/Shared/Components/ServerPid/Default.cshtml
@model string

<div>
    <b>Server pid: @Model</b>
</div>

server.admintool/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - server.admontool</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="p-2">
    <!--<header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication1</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Server" asp-action="Index">Server</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>-->
    <header>
        <div>
            <h1 class="text-center border-secondary" style="border:5px solid black">SCD ADMIN TOOL</h1>
        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!--<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - WebApplication1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>-->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>